### ISSUE TITLE
Planetensuche / broken images

### ISSUE THREAD

**Issue by koarl0815** [gigabyte1977/oddb2#3]
Im Suchergebnis werden anstelle der Planetenbilder brogen images angezeigt. Ich bin eigentlich davon ausgegangen, dass nur Grafiken fehlen, aber die sind eigentlich da. Aus irgendeinem Grund wird http://oddb.frozen-media.de/img/planeten/0.jpg versucht auszuliefern. 

Gibt's da vielleicht irgendein Mapping Plani : Bild, das für die neue Runde noch angepasst werden muss?

**Comment by frozen-media-tz** [comment]
Typ wurde nicht richtig geparst - angepasst.
Behoben mit Commit -> R13 - Plugins OrbitOverlay sichtbar, Tooltip oddb auf Menupfeil, Plan…

**Comment by koarl0815** [comment]
hm, gibts da vielleicht nen folgefehler?
http://oddb.frozen-media.de/index.php?p=search&s=1&un=scharfe+wanda - da sind noch ein paar broken images in der liste?
