### ISSUE TITLE
Kommentare von Planis in der Systemansicht

### ISSUE THREAD

**Issue by koarl0815** [gigabyte1977/oddb2#4]
Ich weiß leider nicht mehr genau, wie das früher war, aber ich bilde mir ein, dass die ODDB in der Systemansicht auch die Kommentare von Planis on mouseover angezeigt hat(?)

Heute bei der Galaöffnung ist jedenfalls aufgefallen, dass die Anzeige von Kommentare wie "Kolo ODA" beim Plani suchen recht hilfreich wären.

Bsp.:
http://www.omega-day.com/game/?op=system&sys=1231

**Comment by frozen-media-tz** [comment]
Es gibt nun 2 Overlay Popups. 
Eines über dem Planet --> interne DB
Zweites bei Mouseover über dem Button(Pfeil) neben jedem Planeten der oddb --> oddb (war früher über Planet, geht aber nicht mehr - dort sollte der Kommentar unverändert drin sein)
Getestet mit diesem System - geht (Popup über Pfeil)
