### ISSUE TITLE
Geparste Kolos werden überschrieben

### ISSUE THREAD

**Issue by koarl0815** [gigabyte1977/oddb2#5]
- Kolo eines anderen Spielers bei Systemeinsicht scannen --> wird richtig in der ODDB erfasst
- Danach ohne Einsicht nochmal das System aurufen --> Kolo wird zwar noch angezeigt, wird im Zuge des Aufrufs in der DB überschrieben
- Nochmal das System aufrufen --> Kolo wird nicht mehr angezeigt

unpraktisch :-(

**Comment by koarl0815** [comment]
Hab das Tool installiert, konnte allerdings leider noch keine fremde Kolo finden, um es zu testen.

Was mir aber aufgefallen ist: http://www.omega-day.com/game/?op=orbit&index=1165 - beim Aufruf eines Orbits mit meinem BBS gibt das Plugin einen Fehler aus:
Parse Quelltext... Konnte Name und ID nicht ermitteln!

**Comment by frozen-media-tz** [comment]
Sollte mit V ..6 (0c5e8646f189d3a2f0a4037b5a1f46a8da5284c6) behoben sein.
Orbit trennt nun nach Unbekannt, in DB/keine Einsicht, Einsicht vorhanden.
Orbit mit BBS von mir funktionierte
Daten sollten nicht mehr überschrieben werden - lag an dem neuen Status "in DB/keine Einsicht" der bisher nicht bekannt war.
